#!/bin/bash
#SBATCH --job-name=em10_seqonly
#SBATCH --partition=compsci
#SBATCH --cpus-per-task=4
#SBATCH --mem=96G
#SBATCH --time=8:00:00
#SBATCH --output=/usr/project/xtmp/nd141/programs/roboNhat_w_new_changes_claude/analysis/logs/em10_seqonly_%j.out
#SBATCH --error=/usr/project/xtmp/nd141/programs/roboNhat_w_new_changes_claude/analysis/logs/em10_seqonly_%j.err

# EM training with the FIBER layers off -- the sequence-only mirror of
# sbatch_train_em10_fiber.sh. Gives seq+em10 a prior fitted under the same emission model
# it decodes with, instead of borrowing robocop_train_em10_chrII (fitted with both layers).

source /home/users/nd141/miniconda3/etc/profile.d/conda.sh
conda activate robocop-2024

set -eo pipefail

cd /usr/project/xtmp/nd141/programs/roboNhat_w_new_changes_claude/analysis

export MPLBACKEND=Agg
export R_HOME=/home/users/nd141/miniconda3/envs/robocop-2024/lib/R

OUT=robocop_train_em10_chrII_seqonly

# Refuse to write into any trainDir that already exists -- an earlier version of this
# script was generated by a sed chain that silently left the fiber trainDir's path in
# place, which would have overwritten robocop_train_em10_chrII_fiber.
if [ -e "$OUT" ]; then
    echo "ERROR: $OUT already exists; refusing to overwrite. Move it aside first." >&2
    exit 1
fi

echo "Host: $(hostname)  Start: $(date)"
echo "OUT=$OUT"
python train_em10_seqonly.py coord_train_chrII_20.tsv "./$OUT/"
echo "End: $(date)"
